;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(load "my-math-funcs.lisp")

(defun sum-even-fib (limit &optional (iter 1) (sum 0))
  (let ((fib (fibonacci iter)))
    (if (<= fib limit)
        (if (evenp fib)
            (sum-even-fib limit (1+ iter) (+ sum fib))
            (sum-even-fib limit (1+ iter) sum))
        sum)))
